spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:3306/netincomesimulator
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

# ログ出力レベルの設定
logging:
  level:
    root: WARN
    org.springframework: INFO
    com.lifehackaid: DEBUG

# jsessionidをクエリストリングに載せないためにURLリライティングを無効化。
server:
  servlet:
    session:
      tracking-modes: cookie
      
# アプリケーション関連の設定
app:
  business:
    tax:
      residentTaxRate: 0.1
      calcSpecialReconstructionIncomeTaxRate: 0.021
      incomeTaxThresholdList: 1000, 1950000, 3300000, 6950000, 9000000, 18000000, 40000000
      incomeTaxRateList: 0.05, 0.10, 0.20, 0.23, 0.33, 0.40, 0.45
      incomeTaxDeductionList: 0, 97500, 427500, 636000, 1536000, 2796000, 4796000
