# docker-compose up -d

version: "3"  # Docker Composeのバージョン

services:  # サービスの定義

  db:  # データベースサービスの定義
    image: mysql:8.0.33  # 使用するMySQLコンテナのイメージ
    restart: always  # コンテナが異常終了した場合に自動的に再起動する設定
    environment:  # コンテナ内で使用する環境変数の設定
      MYSQL_ROOT_PASSWORD: hogehoge  # MySQLのルートユーザーのパスワード
      MYSQL_PORT: 3306  # MySQLのポート番号
      MYSQL_DATABASE: netincomesimulator  # MySQLのデータベース名
    ports:
      - 3306:3306  # ホストマシンとコンテナの間でポートをマッピングする設定
    volumes:
      - devmysql:/var/lib/mysql  # ボリュームのマウント設定
    networks:
      - devnetwork  # コンテナが接続するネットワークの指定
    container_name: devmysql  # コンテナの名前

  web:  # Webサービスの定義
    image: eclipse-temurin:17.0.7_7-jre-alpine  # 使用するJavaランタイムコンテナのイメージ
    volumes:
      - ./build/libs/NetIncomeSimulator-0.0.1-SNAPSHOT.jar:/NetIncomeSimulator-0.0.1-SNAPSHOT.jar  # ホストマシンのファイルをコンテナ内にマウントする設定
    command: ["java", "-jar", "/NetIncomeSimulator-0.0.1-SNAPSHOT.jar"]  # コンテナ内で実行されるコマンドの指定

    ports:
      - "8080:8080"  # ホストマシンとコンテナの間でポートをマッピングする設定
    depends_on:
      - db  # サービスの起動順序を指定する設定（この場合、dbサービスが先に起動する）
    networks:
      - devnetwork  # コンテナが接続するネットワークの指定
    container_name: netincomesimulator  # コンテナの名前

networks:  # ネットワークの定義

  devnetwork:
    name: devnetwork  # 新しいネットワークの名前
    
volumes:
  devmysql: